### ISSUE TITLE
Pro version

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#10]
Alexander, I decided to stick with your BlogMX, but it is lacking many features of full fledged blogging platform.

Here are the other Blog extensions for M2:
https://github.com/IhorVansach/Blog-Extension-for-Magento-2
https://www.magearray.com/blog-magento-2-extension.html
https://www.solwininfotech.com/product/magento-2-extensions/advanced-blog-magento-2/

I suggest you making paid extension based on the BlogMX, as an addon for the BlogMX, that extends Free BlogMX functionality. So, whoever uses your extensions can have a viable blogging solution....

I will cash out $100-200 for a Pro version that has everything imaginable!

**Comment by volodymyr-d** [comment]
@devdesco-ceo We are going to develop only free version of our blog. But we are ready to include in this extension all important features. Please, give us a list of missing features. And we will try to add them.

**Comment by devdesco-ceo** [comment]
Thank you for update. Will post features requests then.
