### ISSUE TITLE
CJA-958-70945 - limit box appeared twice on toolbar.

### ISSUE THREAD

**Issue by bruvinsky** [mirasvit/module-blog#100]
- [ ] limit box appeared twice on toolbar.
- [ ] limit does not work

![scr_02](https://user-images.githubusercontent.com/11726895/36720386-8f17f378-1bb0-11e8-991d-b2e36f71911f.png)

demo
http://blog.m2.mirasvit.com/blog/?limit=50

**Comment by embed0** [comment]
This blog is unusable on production environment until this is fixed.

**Comment by wjpbill** [comment]
I have the same issue, any update on this?

![capture](https://user-images.githubusercontent.com/39123930/39813267-a22c8f8c-5387-11e8-8514-0beb6ce4a41a.PNG)

**Comment by wjpbill** [comment]
It's being caused by line 8 in 

module-blog\view\frontend\templates\post\list\toolbar.phtml

It's not even written the same code standard as the rest of the module and looks like someone added it 

I've removed it from mine and all ok now
