### ISSUE TITLE
Latest version breaks bin/magento setup:di:compile

### ISSUE THREAD

**Issue by ghost** [mirasvit/module-blog#110]
diff --git a/vendor/mirasvit/module-blog/Model/Post/Attribute/Source/Status.php b/vendor/mirasvit/module-blog/Model/Post/Attribute/Source/Status.php
index e8cebc2..bfc5c3f 100644
--- a/vendor/mirasvit/module-blog/Model/Post/Attribute/Source/Status.php
+++ b/vendor/mirasvit/module-blog/Model/Post/Attribute/Source/Status.php
@@ -4,8 +4,7 @@ namespace Mirasvit\Blog\Model\Post\Attribute\Source;
 use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
 use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
 use Magento\Framework\Data\OptionSourceInterface;
-\Magento\Framework\Debug::backtrace();
-die();
+
 class Status extends AbstractSource implements SourceInterface, OptionSourceInterface
 {
     const STATUS_DRAFT = 0;

**Comment by adrok** [comment]
Issue was solved in version 1.0.24
