### ISSUE TITLE
You have an error in model "Config" (Mirasvit\Blog\Model\Config)

### ISSUE THREAD

**Issue by andrewbess** [mirasvit/module-blog#112]
Hey guys.
Are you sure in this code?
https://prnt.sc/kngn6f

**Comment by adrok** [comment]
Yes, our error after recent refactoring. I have removed this method (it was unused)

**Comment by andrewbess** [comment]
@adrok .
Sorry, but you are using this code in template "receipt.phtml" so far.

**Comment by adrok** [comment]
@andrewbess I added changes to recent.phtml too.
