### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getId() on boolean

### ISSUE THREAD

**Issue by Sil-B** [mirasvit/module-blog#113]
Hi i'm getting this error when opening a blog post. Can you help out? 

Using M2.2.4 
`
Fatal error: Uncaught Error: Call to a member function getId() on boolean in /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/mirasvit/module-blog/Model/ResourceModel/Category/Collection.php:129 Stack trace: #0 /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/mirasvit/module-blog/Ui/Post/Source/CategoryTree.php(25): Mirasvit\Blog\Model\ResourceModel\Category\Collection->getRootId() #1 /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(55): Mirasvit\Blog\Ui\Post\Source\CategoryTree->toOptionArray() #2 /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/magento/module-ui/Component/AbstractComponent.php(137): Magento\Ui\Component\Form\Element\AbstractOptionsField->prepare() #3 /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/magento/module-ui/Component/Form/Field.php(98): Magento\Ui\Component\AbstractComponent->prepareChildComponent(Object(Magento\Ui\Component\Form\Element\Select)) #4 /data/ssd/vhosts/staging.xxx in /data/ssd/vhosts/staging.xxx.nl/magento2/vendor/mirasvit/module-blog/Model/ResourceModel/Category/Collection.php on line 129`

**Comment by adrok** [comment]
@Sil-B This error is possible, if you don't have ROOT category in table mst_blog_category_entity.

You should have root category where parent_id = 0

**Comment by Sil-B** [comment]
Hi @adrok thanks for the quick reply! Editing works again. 

If i visit the frontend i'm getting a new error: 

`There has been an error processing your request
Item (Mirasvit\Blog\Model\Post) with the same ID "140" already exists.
Error log record number: 696184268740 `

I i delete the post, the error will just show a new number (and again and again)

**Comment by adrok** [comment]
I suppose database table were wrong. Please send support request to support@mirasvit.com with temporary ssh and backend access and I'll check.

**Comment by Sil-B** [comment]
Oke thanks.
