### ISSUE TITLE
Javascript error when trying to upload picture in a post

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#114]
An additional picture can not be uploaded in a post (magento 2.2.2 - latest blog version). There is a javascript error in the console after pressing the "insert image..." upload button.

![screen shot 2018-09-24 at 13 24 20](https://user-images.githubusercontent.com/16196483/45949747-43355580-bffd-11e8-855d-8d6c661eca65.png)

**Comment by andidhouse** [comment]
Really just closed?

**Comment by adrok** [comment]
I can't reproduce this issue on latest version.
