### ISSUE TITLE
After upgrading to 2.2.6 from 2.2.5

### ISSUE THREAD

**Issue by LucasMali** [mirasvit/module-blog#125]
Update: Needs to be for the module-seo.

Fatal error: Uncaught Error: Call to undefined method Magento\Framework\View\Page\Config\Interceptor::isRemoveNativeRs() in MAGE_ROOT/vendor/mirasvit/module-seo/src/SeoMarkup/Plugin/Frontend/Framework/Controller/Result/RemoveNativeRsPlugin.php on line 79

**Comment by adrok** [comment]
Hello Lucas,

This issue related with SEO module, you need run bin/magento setup:di:compile and also clear all magento caches.
