### ISSUE TITLE
Posts Widget

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#13]
Can you extend your recent posts widget to be able to create a widget with recent posts through Content>Widgets part of admin in order to be able to inject the widget oi home page and other pages across M2?

Slider (owl carousel), static block, etc with options to choose just Titles, Titles with Images, etc for display?

Examples of premium extensions:
http://magedemo.solwininfotech.com/magento2/extension/cms/sim2ab/ourblog/

**Comment by adrok** [comment]
I added widget Blog MX: Recent Posts

**Comment by devdesco-ceo** [comment]
Thanks for doing that, but I gues more work has to be done around styling and options for display. :+1:

**Comment by adrok** [comment]
Please clarify, what additional options do you need?
