### ISSUE TITLE
Related products broken in Magento 2.3.0

### ISSUE THREAD

**Issue by judaschwartz** [mirasvit/module-blog#130]
I just installed this module on a clean new instance of magento 2.3.0 and the related products tab when editing a post is broken the message being returned (in network tab) to the browsers request to `https://example.com/index.php/bossMercantile/mui/index/render/key/15edc29870ec5b65299c648bb20135bb82f604d0a6b19ac540e213620347af35/?namespace=blog_post_form_product_listing&isAjax=true` is `{"error":"The &quot;componentType&quot; configuration parameter is required for the &quot;product_columns&quot; component.","errorcode":"0"}`

![image](https://user-images.githubusercontent.com/7826445/51993226-5e691380-247c-11e9-8144-87f88119cf72.png)

![image](https://user-images.githubusercontent.com/7826445/51992928-e4388f00-247b-11e9-827e-24a5bf6242fc.png)

**Comment by adrok** [comment]
I've just tested latest extension version 1.0.28 with M 2.3.0 and Related Products functionality is working: 

![image](https://user-images.githubusercontent.com/1307119/51995199-ec63ef00-24ba-11e9-81e7-0dc83ef7f398.png)

Please check installed extension version.
