### ISSUE TITLE
Uncaught Error class SaveAndContinueButton not found

### ISSUE THREAD

**Issue by JesKingDev** [mirasvit/module-blog#136]
Unable to create a new blog post - getting an error when loading the Add New Post page.

> Fatal error: Uncaught Error: Class 'Mirasvit\Blog\Ui\Post\Form\Control\SaveAndContinueButton ' not found in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 Stack trace: #0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mirasvit\\Blog\\U...', Array) #1 vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Mirasvit\\Blog\\U...', Array) #2 vendor/magento/framework/View/Element/UiComponent/Control/ButtonProviderFactory.php(39): Magento\Framework\ObjectManager\ObjectManager->create('Mirasvit\\Blog\\U...', Array) #3 vendor/magento/fr in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

**Comment by JesKingDev** [comment]
Appears this was fixed in https://github.com/mirasvit/module-blog/commit/48340876da1711c71521301f4850940a5b088353 and in version 1.2.9 however Packagist doesn't show 1.2.9 yet and a composer update doesn't pull it.

**Comment by judaschwartz** [comment]
@JesKingDev  packagist has been updated
