### ISSUE TITLE
Create tag up for commit on master and update packagist version

### ISSUE THREAD

**Issue by judaschwartz** [mirasvit/module-blog#138]
@adrok Whats the story with packagist? 
https://packagist.org/packages/mirasvit/module-blog
I see that the version there hasn't been updated to 1.0.29 also if you could Bump the version number so the last commits are included?

**Comment by adrok** [comment]
I've updated package on packagist.org

**Comment by judaschwartz** [comment]
@adrok thanks 👍 
Can you please also update the tag to 1.0.30 to include the latest commits?

**Comment by adrok** [comment]
I released 1.0.30
