### ISSUE TITLE
Tags not saving in admin.

### ISSUE THREAD

**Issue by pauldonnelly** [mirasvit/module-blog#140]
When you add a new Tag, or existing tag and click Save & Continue. The tag does not save or display in the admin.
As you can see, I added Home as a tag, clicked save and the tag disappears.

![Screen Shot 2019-04-04 at 13 26 38](https://user-images.githubusercontent.com/1893180/55555529-5d9f6880-56dd-11e9-8534-b2338f9fd678.png)
![Screen Shot 2019-04-04 at 13 26 56](https://user-images.githubusercontent.com/1893180/55555536-61cb8600-56dd-11e9-94da-093ba82589ac.png)

**Comment by NikolasSumrak** [comment]
I have a fix for it here https://github.com/mirasvit/module-blog/pull/142

**Comment by adrok** [comment]
I've merged fix to master.
