### ISSUE TITLE
How can we remove this link: is it in settings?

### ISSUE THREAD

**Issue by seansan** [mirasvit/module-blog#145]
How can we remove this link: is it in settings?

![image](https://user-images.githubusercontent.com/652395/56227831-a3154b80-6076-11e9-9465-06f376c17f56.png)

**Comment by adrok** [comment]
This is your copyright. You can change it in file vendor/mirasvit/module-blog/view/frontend/templates/html/copyright.phtml

**Comment by seansan** [comment]
maybe make it a setting

I dont think we want outward facing backlinks to mirasvit (although I
understand why you might find this interesting)
