### ISSUE TITLE
#NRC-806-00460 - tag and empty category

### ISSUE THREAD

**Issue by VikMirasvit** [mirasvit/module-blog#146]
Воспроизводится тут http://blog223.qa.mirasvit.com

1. Создаем статью с тэгом. Сохраняется и тэг пропадает в админке и на фронте, остается в бд только
2. Создаем статью без выбора категории (оставляем пустой как есть) . Сохраняем и смотрим в списке категорий появится новая пустая категория.

**Comment by VikMirasvit** [comment]
Install latest version http://bl230.qa.mirasvit.com/blog/ both issue still here.

new issue:  I have a doubt regarding the "tags" For eg : I can add the same tag, suppose "tag_A" to Post_1 and Post_2. But in the listing page I can see "tag_A" twice.

**Comment by adrok** [comment]
@VikMirasvit mirasvit/module-blog dev-develop 282ea15 Mirasvit Blog MX - installed version on qa.

Please install latest version and check these issues.

**Comment by VikMirasvit** [comment]
@adrok here http://blog225.qa.mirasvit.com/ latest version 1.0.31 http://i.imgur.com/b42RYwn.png issues still here

**Comment by adrok** [comment]
@VikMirasvit I updated http://blog225.qa.mirasvit.com/ to dev branch, with few recent fixes. Plz check.

**Comment by VikMirasvit** [comment]
@adrok Create new Article on http://blog225.qa.mirasvit.com/  http://i.imgur.com/0nxIuHe.png 
- new category doesn't appears - ok
- Tags still Missed  http://i.imgur.com/y699mHd.png http://i.imgur.com/NaIDBFJ.png
