### ISSUE TITLE
Blog main page does not sort the blog posts

### ISSUE THREAD

**Issue by digitalbricklayer** [mirasvit/module-blog#148]
I have just upgraded to the latest version (1.0.31) of the blog module on my stage server. The main content of the blog is not sorted by date anymore. The recent list is still sorted by date but the main blog view is not.

The functionality works fine on the live server. The software on the live server is version 1.0.22.

**Comment by adrok** [comment]
By default, we sort all post by 2 conditions: Is Pinned and Updated At date.
I've changed sort by Updated At to Created At.

Version 1.0.32
