### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by VikMirasvit** [mirasvit/module-blog#150]
1. SJW-333-74919 
I'm trying to export a dictionary and I always receive the error "Missed Phrase". Following the instruction there https://mage2.pro/t/topic/2272  I figured out that your extension is
the culprit: 
grep -rnw . -e "__('')" -e '__("")'
./vendor/mirasvit/module-blog/Helper/Form/Post/Storeview.php:108:
                                            label"         => __(""),

2.  ZMD-353-58980 
Support for https://magento.com/products/magento-commerce/page-builder it possible?

3. ACU-053-80634
I have a doubt regarding the "tags" For eg : I can add  the same tag, suppose "tag_A" to Post_1 and Post_2. But in the listing page I can see 2 "tag_A". Is this is the expected behaviour? Normally we can use same tag for multiple posts but in the listing page it
should not replicate. 
Can't check, here http://lblog.qa.mirasvit.com/ latest extension version but issue with missed tags still here.

**Comment by evs-xsarus** [comment]
Developerinfo for the Page Builder: https://devdocs.magento.com/page-builder/docs/

**Comment by adrok** [comment]
@evs-xsarus I didn't find ability to install page builder on 2.3.1 CE. (github repo from contributor docs is not available anymore)

On EE, Page Builder is working:

![image](https://user-images.githubusercontent.com/1307119/58243616-9f51a480-7d59-11e9-9541-803ffbf885b2.png)
![image](https://user-images.githubusercontent.com/1307119/58243635-aa0c3980-7d59-11e9-9b83-91755b32f33e.png)

**Comment by evs-xsarus** [comment]
@adrok good to know. The page builder isn't (yet?) available for CE.

**Comment by adrok** [comment]
@evs-xsarus https://magento.com/blog/magento-news/magento-acquires-technology-behind-bluefoot-cms-page-builder

> Magento will be providing more details on the integration roadmap in Q1 2017. In the meantime, the current version of Bluefoot CMS (v1.0) will be available exclusively for licensed Magento Enterprise Edition or Enterprise Cloud Edition merchants with Magento version 2.1 and up. Merchants can obtain the extension through their CDM or Account Manager.

**Comment by VikMirasvit** [comment]
1. SJW-333-74919
I'm trying to export a dictionary and I always receive the error "Missed Phrase". Following the instruction there https://mage2.pro/t/topic/2272 I figured out that your extension is
the culprit:
grep -rnw . -e "('')" -e '("")'
./vendor/mirasvit/module-blog/Helper/Form/Post/Storeview.php:108:
label" => __(""),

3. ACU-053-80634
I have a doubt regarding the "tags" For eg : I can add the same tag, suppose "tag_A" to Post_1 and Post_2. But in the listing page I can see 2 "tag_A". Is this is the expected behaviour? Normally we can use same tag for multiple posts but in the listing page it
should not replicate.
Can't check, here http://lblog.qa.mirasvit.com/ latest extension version but issue with missed tags still here.

**Comment by adrok** [comment]
@VikMirasvit  closed (already fixed)

**Comment by VivekShingala** [comment]
Hi, I have installed this module recently and facing one issue with edit button.

For all the components, edit icon is not working. There is no console errors or warnings in the browser but it just does nothing. Please refer the image below.

![image](https://user-images.githubusercontent.com/17267929/60494197-f12c0980-9ccb-11e9-8bf0-b68e19c64384.png)

How to fix it?

PS: all the other icons (buttons) are working fine. Just edit icon is not working.
