### ISSUE TITLE
Some suggestions on the blog module

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#16]
Many thanks first for this module! 

I have some suggestions:
- Have a max per page post number in blog categories and home before the paging is activated in the backend
- Link all blogpost images in the listings and sidebar (recent posts) as user tend to click on the images and not on the text first
- also "add this" is deactivated in the backend it is shown on the blog category pages listings - this should be removed here as well
- add possibility to have the global choice between blogpost urls which have a trailing slash and a ".html"

http://www.domain.de/blog/post-3/ 
or
http://www.domain.de/blog/post-3.html

**Comment by adrok** [comment]
Solved points 2,3,4 in version 1.0.4

Point 1 moved to dev plan.

**Comment by andidhouse** [comment]
Wow great - that was quick 👍 
Just one small thing regarding the URLs

Now if you type in for example ".html" also the category urls get the ".html" ending. 
Maybe it is possible to have two fields here for Blogposts and Blog Categories?

I am asking because the best ending from a seo point of view for an article or blogpost is at the moment an .html ending and a category should have in best case a trailing slash "/" at the end.
Also i think this reflects most of the shops URL structure for shop categories and products.

**Comment by adrok** [comment]
I can implement this. What about urls for tags and authors?

**Comment by andidhouse** [comment]
Hi Alexander,

for Tags:
As this is a listing page of all tag sites a trailing slash would be best. 
But more important would be an option to set a possibility for tag sites either to have them indexed or not via the metatag:

Index Tags / Noindex Tags: 
- <meta name="robots" content="no-index, follow" />
- <meta name="robots" content="index, follow" />

As it is now you can´t edit a tage page at all (which is ok as it is not so important for a blog - just for very big blogs or very SEO optimized blogs ;-)). So the best would be to have an global switch to index or no index tag-sites at the moment for your blog.

For the authors pages it is the nearly the same:
As you have no influence to edit an author page at the moment (author text description, author picture and Meta-tags like Author Site Title, Author Meta Description etc.) i think it would be best to have the same option here like for the tags. 
Url ending a trailing slash but the author name in the url:

Not:
http://www.domain.de/blog/author/1/
but
http://www.domain.de/blog/author/name-of-the-author/

**Comment by andidhouse** [comment]
If you want to make it perfect:

Backend option for: 
- Show author Link at the frontend / or not
- Show category links (at listing pages and below each blogposts) / or not
- Show date at blogpost (listing and blogpost itself) / or not

**Comment by devdesco-ceo** [comment]
These guys from Mirasvit are fantabulous! :+1:

**Comment by andidhouse** [comment]
absolut! best magento extensions by far and best service as well! 👍

**Comment by devdesco-ceo** [comment]
Man, I am so astonished by the service! I am myself Ukrainian, and these guys as well.
Another very good M2 developer is Amasty. These guys are from Belarus. 

I am hooked on these two companies.

Have got a lot of scam coming from India-based developers that are approved by Magento.
Also, a guy to stay away from is the http://www.iksanika.com/ - that guy is real pirate - he is ripping off other one's extensions that are broken in the end. I had to fight him through PayPal and won the case.
Another bad guys worthy to mention - cedcommerce.com - same crap!

**Comment by commcad** [comment]
I have to echo what @andidhouse and @devdesco-ceo said

Mirasvit is a legend from my perspective. BLOG MX is so bloody nice it now creates a huge confusion for us here. Changes everything; "we are debating now whether to have Magento 2.0 converted as a BLOG platform" similar to what Wordpress is. Meaning making BLOG MX the home page basically and having (relevant) products showing at the footer of each blogs. 

FEATURE I would recommend (or happy to pay for anyday) is the option to add product(s) at the footer of the blog. Just above the commentary box. Recently seen other Blog extensions with this feature and tough it was a great idea (I didn;t invent that idea).

I know I could get around by placing widgets and all, but if BLOG MX would give the option from the Add New Post page that'd be absolutely brilliant.

Anyway. KUDOS to Alexander for a great extension. I hope Mirasvit.com gets famous for the share. Worth telling everybody you know and posting on your favorite Magento related forums. Help the guy and the Co please

Thanks again

**Comment by adrok** [comment]
@commcad version 1.0.6-alpha1 - added ability to relate post with products.

Example: http://blog.m2.mirasvit.com/blog/get-creative-with-the-lbd.html

**Comment by commcad** [comment]
Sick stuff mate, '<size1,000>' YOU ARE A LEGEND '</i mean it>'

**Comment by Orims14** [comment]
Hi @adrok 
Many thanks for this wonderful module. I was hoping if it's possible to have different frontend template options to pick from in the admin either by category or for the entire blog. Currently the examples show just a list view where by you have the hero on left the content on right.
If there could also be a grid type template where we can have image, excerpt, tags with options to set posts per grid. This will be appreciated.

Or will it be better to just extend it on a local module?

Thank you.
