### ISSUE TITLE
Nicest and coolest M2 Blog around, bravo

### ISSUE THREAD

**Issue by commcad** [mirasvit/module-blog#20]
I've just installed your Blog successfully using the cmd install method you've wrote. Flawless! Best extension around, it revamps the entire store with life. Thanks x100!!  

Slight problem however, M2.05 complains about missing dependencies when trying to update itself to 2.06. Show a no-name module entry at the top list and Mirasvit/blog module shows disabled at the very bottom... although everything seems to be running fine in the front & back end.

Strange. Does magento block official upgrades if we install any pckg from anywhere else other than 'their' Marketplace? Feels like it anyway

Thanks

**Comment by adrok** [comment]
Try copy vendor/mirasvit/module-blog/composer.json to vendor/mirasvit/module-blog/src/Blog/composer.json

`cp vendor/mirasvit/module-blog/composer.json vendor/mirasvit/module-blog/src/Blog/composer.json`

**Comment by commcad** [comment]
Omg, it works. Thanks for the easy to copy/paste cmd by the way. 

Won't say this enough but so far, and I've tried/paid for about 5 extensions (testing), your Blog MX add-on is by far the best on the internet right now Alexander. We've searched quite a lot these last 10 days. 

The best in terms of "added value" to Magento 2 anyway (SEO, customer enrollment, store life, etc...). Magento should buy this license off you and make it standard Magento module in all honesty.

Again, BRAVO mate and thanks for sharing with the community

> > > > https://mirasvit.com/magento-2-extensions.html
> > > > Count me in for RMA and Adv. Report extension. But not before I get 2.06 working flawlessly (not as easy as we tough it would have been this Magento 2)

thx again

**Comment by commcad** [comment]
Alexander - how can we get BLOG MX inside Magento Marketplace as a standard and official extension pckg?  It's urgent lolll

If I understand, once you've clone GIT you can't use the official Magento's Web Setup Wizard for upgrades anymore. All will need to be manually done by cmd, which is not an option for us here sadly. We need to retain the official functions of Magento as much as we can. Long story :/

Is there any way around this?! We need your BLOG MX + the Web Setup Wizard functionality

How how how???

**Comment by commcad** [comment]
You know what, I think I found how. You just need to copy composer.json.old, remove the BLOG MX stuff from it, and save as composer.json > then run Web Setup Wizard. Just tried and it worked.

Can you confirm this is the best way forward? Sorry for bothering you with this mate

**Comment by adrok** [comment]
These issue related with not default repository structure.

I released version 1.0.5 with changed repository structure and moved package to packagist.org.

Update process (just once):

`composer remove mirasvit/module-blog`
remove github section from composer.json https://github.com/mirasvit/module-blog
`composer require mirasvit/module-blog`

now composer will use native package list (https://packagist.org/packages/mirasvit/module-blog)

Also you can use magento setup/update wizard for update magento and blog module:
http://screencast.com/t/ueDNvvIf3

**Comment by commcad** [comment]
This is crazy stuff... it works. Thanks Alexander (dunno what to say man)

PS: BLOG MX Is SIMPLY BEAUTIFUL (btw). We are actually debating about converting Magento 2 into a 'Wordpress type' application, instead of a ecommerce frontend. I'll send you the URL of our store when I have something to show (offline now, dev mode).

They say good things about you there btw: https://community.magento.com/t5/Version-Upgrades-for-2-x/Updating-from-any-2-x-to-2-06-kills-the-Web-Setup-Wizard/m-p/37294/highlight/false#M277

**Comment by commcad** [comment]
Alex - found a bug !!!!! Knew this couldn't be as perfect as it seemed ;) 

1. > Content > All Posts > Add New Post > In the left hand side, the Category does not display
2. > Content > All Posts > Action are missing (edit/delete)

Tested in 2.0.5 and 2.0.6. Both the same. Backend issues only, works and display just fine in the frontend.

Trace from when you click on > Content > All Posts > 

The "/var/www/domain.com/" file doesn't exist or not a file 
#0 /var/www/domain.com/vendor/magento/framework/Filesystem/Directory/Write.php(146): Magento\Framework\Filesystem\Directory\Write->assertIsFile(false) 
#1 /var/www/domain.com/vendor/magento/framework/App/View/Asset/MaterializationStrategy/Symlink.php(30): Magento\Framework\Filesystem\Directory\Write->createSymlink(false, 'adminhtml/Magen...', Object(Magento\Framework\Filesystem\Directory\Write)) 
#2 /var/www/domain.com/vendor/magento/framework/App/View/Asset/Publisher.php(66): Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink->publishFile(Object(Magento\Framework\Filesystem\Directory\Write), Object(Magento\Framework\Filesystem\Directory\Write), false, 'adminhtml/Magen...') 
#3 /var/www/domain.com/vendor/magento/framework/App/View/Asset/Publisher.php(50): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File)) #4 /var/www/domain.com/vendor/magento/framework/App/StaticResource.php(109): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File)) 
#5 /var/www/domain.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch() 
#6 /var/www/domain.com/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource)) 
#7 {main}

**Comment by commcad** [comment]
WAIT Alex

I save the script on my server and BASH it manually and all works perfectly now so I think the problem is "at my end". Either Magento needs to be recompiled, index refresh manually or cache clear/flush manually. Not sure which one so I am checking now. I know it should be 'refreshed' anyway but for rookies like me, new to Magento, you may want to update your installation steps with the refresh it needs.

http://stamster.github.io/magento2-commander.sh

PS: BLOG MX Is SIMPLY BEAUTIFUL (btw). We are actually debating about converting Magento 2 into a 'Wordpress type' application, instead of a ecommerce frontend. I'll send you the URL of our store when I have something to show (offline now, dev mode).

I'll report back on what needs to be refreshed exactly for that picky Magento 2.0 to work first try (for Rookie version lolll).

**Comment by commcad** [comment]
Let's hope they keep it up
https://community.magento.com/t5/Theming-Layout-Design-Questions/NEWS-BEST-MAGENTO-2-0-BLOG-EXTENSION-MIRASVIT-COM/m-p/37396/highlight/false#M474
