### ISSUE TITLE
No main navigation visible on blogposts when varnish is active

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#22]
When varnish cache is active and you look at a blogpost the main navigation is gone.
In the blog root and in the categories the main navigation is visible.

This only appears with varnish cache active.

**Comment by commcad** [comment]
I bet Mirasvit (Alex) are busy re-writing their code for the launch of M2.1 this mid-June :/ I just wish I could help but can only wish. Annoying!

We run 2.1rc here for testing purposes (paypal flow, etc) so we can't have the BLOG MX enabled. Getting the can't "_resolved to an installable set of packages_". Same thing for pretty much all the other extensions we have from other developers. Don;t know what Magento are up to with 2.1 in all honesty. Must be chaos for these good will developers atm. 

**Varnish?!** Man, none of my business, but you want to get things rolling on NGINX (HTTP2/HSTS) PHP7-FPM and REDIS. You wouldn't believe how bullet fast it is over HTTP2 & TLS1.2. (no more unreliable POUND/Stunnel bullsh*t to deal with anymore). Its basically 3x faster than having no encryption onto apache. Let me know if you need help with virtual host scripts for nginx and cfg files for redis, I got it all up and running atm on the new Ubuntu 16.04, happy to share.

**Comment by adrok** [comment]
@commcad I released alpha versions for blog and blog-sample-data, module can be installed on 2.1 now, frontend part works correct, backend part - few issues related new UI interfaces.

@andidhouse I still try reproduce issue with varnish, but without luck.

**Comment by commcad** [comment]
Alex, just installed successfully. Still look and function as good as the first time, THANKS ;)
Not sure what you mean RE 'backend issues'. Works perfectly at my end. If I find anything in the logs backend-wise I'll report back but so far so good bud.

Keep up the amazing work and thanks x1000 again! 

ps> pls make sure Mirasvit's extensions are running as good as blog mx for this June's M2.1 release. We have 4 in our wish list ;) Can't wait!
