### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by matt-bailey** [mirasvit/module-blog#23]
Hi. If you try to access a blog post page and haven't set up any tags yet you get the following error:

```
Warning: Division by zero in /.../vendor/mirasvit/module-blog/view/frontend/templates/sidebar/tag_cloud.phtml on line 10....
```

I guess you just need to have a check that allows zero tags.

**Comment by adrok** [comment]
I added fix to version 1.0.6-alpha7
