### ISSUE TITLE
Installation fails if installed at the same time as new M2 site

### ISSUE THREAD

**Issue by matt-bailey** [mirasvit/module-blog#24]
If you add the blog module to your core `composer.json` file and then try to set up a site from scratch with `php ./bin/magento setup:install [options]` the setup process fails with the following error:

![screenshot 2016-06-01 11 31 46](https://cloud.githubusercontent.com/assets/969385/15707045/81313628-27ee-11e6-87a3-5b7667275882.png)

So basically it's not possible to install the blog module at the time of setting a site up from scratch, you need to install it after you have a site up-and-running.

Is there a way round this (we have a core set of third party modules that we would like to install right at the start of setting up a new project)?

**Comment by adrok** [comment]
Sorry, I not test installation blog with setup command only upgrade. Within day I'll check.

**Comment by matt-bailey** [comment]
You are a star, Thank you! I can confirm this error now no longer occurs.
