### ISSUE TITLE
Magento 2.1.0 - Serialization of 'Magento\Framework\View\Layout\Element' is not allowed

### ISSUE THREAD

**Issue by webspeaks** [mirasvit/module-blog#25]
I updated my site to Magento 2.1.0. After that the module started giving errors.
When opening the blog index or blog post page, I get this error in system.log

`[2016-06-25 10:21:41] main.CRITICAL: Serialization of 'Magento\Framework\View\Layout\Element' is not allowed [] []`

The content on listing page and blog view page is not visible at all.

Please help.

Thanks

**Comment by adrok** [comment]
I fixed this bug and released new version 1.0.6

`composer update mirasvit/module-blog`
