### ISSUE TITLE
Search by Mirasvit Sphinx Search Ultimate 

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#3]
Feature request:
Add ability to get blog indexed and searched by Mirasvit's Sphinx Search Ultimate  extension for M2

**Comment by adrok** [comment]
Added internal search to blog and integrated with Sphinx Search Ultimate, Advanced Sphinx Search Pro (version 1.0.9)

**Comment by devdesco-ceo** [comment]
Thanks a lot!
