### ISSUE TITLE
Problem with author page

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#32]
When we click at a author page like /author/1/ this error is shown in the frontend:

Magento 2.1 / Redis / Varnish / php7 / nginx

Fatal error: Uncaught Error: Call to a member function getName() on null in /var/www/html/magento2/vendor/mirasvit/module-blog/Block/Author/View.php:48 Stack trace: #0 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(264): Mirasvit\Blog\Block\Author\View->_prepareLayout() #1 /var/www/html/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor)) #2 /var/www/html/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #3 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #4 /var/www/html/magento2/var/generation/Magento/ in /var/www/html/magento2/vendor/mirasvit/module-blog/Block/Author/View.php on line 48

**Comment by adrok** [comment]
@andidhouse did you have admin user with ID=1 (Author of this post)?

**Comment by andidhouse** [comment]
@adrok 

Yes - ID=1 of this post

**Comment by adrok** [comment]
I can't reproduce this issue on local environment. If author is NULL, then controller must redirect to 404.

Please send request to support@mirasvit.com with temporary access to store.
