### ISSUE TITLE
Editing post not working?

### ISSUE THREAD

**Issue by AhVSag** [mirasvit/module-blog#33]
When we create a post and try to edit it later, the post content does not change. We had a typo in one word and were not able to edit the post. The post is saving, but the content remains the old.

**Comment by adrok** [comment]
@AhVSag What magento version you use?

**Comment by AhVSag** [comment]
magento/product-community-edition 2.1.0

**Comment by adrok** [comment]
I can't reproduce this issue on local environment, probably it related with cache.
