### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mathewhellums** [mirasvit/module-blog#34]
First, I'd like to say that this is by far one of, if not, **_the_** best blog extension available for Magento 2.

Are there plans to take advantage of service contracts to create a public facing API? I'd like the blog to be consumable (export/import data) from other endpoints on the web.

**Comment by adrok** [comment]
Yes, we already refactoring blog code and will implement web API in next major release (~ 1-2 weeks)

**Comment by bramvanderholst** [comment]
👍
