### ISSUE TITLE
Multi-store compatability

### ISSUE THREAD

**Issue by pascaladriaansen** [mirasvit/module-blog#35]
First of all, thanks for this awesome free module!

I do have a suggestion though. Would it be possible to add multi-store compatability? Meaning that we can choose which post is published in which website / store / store view (much like how CMS Pages or CMS Blocks can be published to specific websites / stores / store views). That would allow us to also use this module in our multi store / multi language setups.

Thanks!

**Comment by pascaladriaansen** [comment]
@adrok any idea if this could be implemented?

**Comment by adrok** [comment]
@pascaladriaansen Yes, I already start this feature, we need ~ 1 week for release.

**Comment by pascaladriaansen** [comment]
That's awesome! Looking forward to it. Thanks :) 👍

**Comment by fwegberts** [comment]
When is it finished, waiting for it :)

**Comment by RomanZh** [comment]
done

**Comment by pascaladriaansen** [comment]
Awesome! @RomanZh when will this be released?

**Comment by RomanZh** [comment]
@pascaladriaansen It will be released this week
