### ISSUE TITLE
Autolinks for Advanced SEO Suite for Magento 2

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#4]
Alexander, please consider adding ability to create auto links for your Blog MX via your PAID Autolinks extension in Autolinks for Advanced SEO Suite for Magento 2.

**Comment by adrok** [comment]
Advanced Seo Suite / Seo Autolinks (version 1.0.1-alpha5) compatible with Blog MX now.

**Comment by devdesco-ceo** [comment]
Thanks! :+1:

**Comment by devdesco-ceo** [comment]
Can you also integrate it with your Advanced Sitemap module?
