### ISSUE TITLE
Author page with error when varnish caching is active

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#40]
Hi there,

when we click on the author page link for example .../author/1/ and caching is deactivated all is fine.
If we activate caching (in our case varnish caching is active) the following error is shown on the page in the frontend. Maybe this has something to to with the navigation as this is exactly shown where the main navigation is:

Fatal error: Uncaught Error: Call to a member function getName() on null in /var/www/html/magento2/vendor/mirasvit/module-blog/Block/Author/View.php:48 Stack trace: #0 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(264): Mirasvit\Blog\Block\Author\View->_prepareLayout() #1 /var/www/html/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor)) #2 /var/www/html/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #3 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #4 /var/www/html/magento2/var/generation/Magento/ in /var/www/html/magento2/vendor/mirasvit/module-blog/Block/Author/View.php on line 48

**Comment by ryan-copeland** [comment]
I am also experiencing this issue. Did anyone find a solution to this problem in the end?
