### ISSUE TITLE
Error: current version - none, required version - 1.0.2

### ISSUE THREAD

**Issue by PaperDS** [mirasvit/module-blog#44]
Installing blog on Magento 2.1.2

Procedure followed below:

composer require mirasvit/module-blog
Using version ^1.0 for mirasvit/module-blog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mirasvit/module-blog (1.0.11)
    Downloading: 100%

php -f bin/magento module:enable Mirasvit_Blog
The following modules have been enabled:
- Mirasvit_Blog

php bin/magento setup:upgrade

rm -rf pub/static/*; rm -rf var/view_preprocessed/*;
php -f bin/magento setup:static-content:deploy

I then get the following error:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Mirasvit_Blog data: current version - none, required version - 1.0.2

**Comment by adrok** [comment]
Please send output for bin/magento setup:upgrade

**Comment by PaperDS** [comment]
[magento5@zodiac public_html]$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/magento5/public_html/var/generation/Composer
/home/magento5/public_html/var/generation/Magento
/home/magento5/public_html/var/generation/Migration
/home/magento5/public_html/var/generation/Symfony
The directory '/home/magento5/public_html/var/di/' doesn't exist - skipping cleanup
/home/magento5/public_html/pub/static/deployed_version.txt
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Module 'Magento_Rule':
Module 'Magento_Catalog':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'Magento_SalesSequence':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Bundle':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_CatalogInventory':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_Checkout':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_CatalogRule':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Vault':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_Captcha':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_OfflineShipping':
Module 'Magento_Authorizenet':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_GoogleAdwords':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Magestore_OneStepCheckout':
Module 'Mirasvit_Blog':
Installing schema... Upgrading schema...
Module 'Wyomind_Core':
Module 'Wyomind_OrderEraser':
Schema post-updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Running schema recurring...
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Module 'Magento_Rule':
Module 'Magento_Catalog':
Running schema recurring...
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
Module 'Magento_Widget':
Module 'Magento_Quote':
Running schema recurring...
Module 'Magento_CheckoutAgreements':
Module 'Magento_SalesSequence':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_CatalogInventory':
Running schema recurring...
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_Checkout':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_ConfigurableProduct':
Running schema recurring...
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_CatalogRule':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Vault':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Magento_Captcha':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_OfflineShipping':
Module 'Magento_Authorizenet':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Running schema recurring...
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_GoogleAdwords':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Running schema recurring...
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Running schema recurring...
Module 'Magestore_OneStepCheckout':
Module 'Mirasvit_Blog':
Module 'Wyomind_Core':
Module 'Wyomind_OrderEraser':
DDL cache cleared successfully



  [Exception]
  Missing write permissions to the following paths:
  /home/magento5/public_html/var/composer_home/cache/vcs/https---github.com-magento-data-migration-tool/objects/pack/pack-9e
  adbc90c0be565cdd03a5dcc6ab341985927e49.pack
  /home/magento5/public_html/var/composer_home/cache/vcs/https---github.com-magento-data-migration-tool/objects/pack/pack-9e
  adbc90c0be565cdd03a5dcc6ab341985927e49.idx
  /home/magento5/public_html/var/composer_home/cache/vcs/https---github.com-magento-data-migration-tool/objects/bb/67dcf58d1
  5cc1d7f6d9ec99dd430ccac3e20b4



setup:upgrade [--keep-generated] [--magento-init-params="..."]


[magento5@zodiac public_html]$ rm -rf pub/static/*; rm -rf var/view_preprocessed/*;
[magento5@zodiac public_html]$ php -f bin/magento setup:static-content:deploy
Requested languages: en_US
Requested areas: frontend, adminhtml
Requested themes: Magento/blank, Magento/luma, Paperweight/paper, Magento/backend
=== frontend -> Magento/blank -> en_US ===
=== adminhtml -> Magento/backend -> en_US ===
=== frontend -> Magento/luma -> en_US ===
..................=== frontend -> Paperweight/paper -> en_US ===
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2207 files; errors: 0
---

New version of deployed files: 1481102095
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2211 files; errors: 0
---

New version of deployed files: 1481102098
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2023 files; errors: 0
---

New version of deployed files: 1481102101
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2283 files; errors: 0
---

New version of deployed files: 1481102104

**Comment by PaperDS** [comment]
[magento5@zodiac public_html]$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/magento5/public_html/var/generation/Composer
/home/magento5/public_html/var/generation/Magento
/home/magento5/public_html/var/generation/Migration
/home/magento5/public_html/var/generation/Symfony
The directory '/home/magento5/public_html/var/di/' doesn't exist - skipping cleanup
/home/magento5/public_html/pub/static/deployed_version.txt
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Module 'Magento_Rule':
Module 'Magento_Catalog':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'Magento_SalesSequence':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Bundle':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_CatalogInventory':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_Checkout':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_CatalogRule':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Vault':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_Captcha':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_OfflineShipping':
Module 'Magento_Authorizenet':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_GoogleAdwords':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Magestore_OneStepCheckout':
Module 'Mirasvit_Blog':
Installing schema... Upgrading schema...
Module 'Wyomind_Core':
Module 'Wyomind_OrderEraser':
Schema post-updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Running schema recurring...
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Module 'Magento_Rule':
Module 'Magento_Catalog':
Running schema recurring...
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
Module 'Magento_Widget':
Module 'Magento_Quote':
Running schema recurring...
Module 'Magento_CheckoutAgreements':
Module 'Magento_SalesSequence':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_CatalogInventory':
Running schema recurring...
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_Checkout':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_ConfigurableProduct':
Running schema recurring...
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_CatalogRule':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Vault':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Magento_Captcha':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_OfflineShipping':
Module 'Magento_Authorizenet':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Running schema recurring...
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_GoogleAdwords':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Running schema recurring...
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Running schema recurring...
Module 'Magestore_OneStepCheckout':
Module 'Mirasvit_Blog':
Module 'Wyomind_Core':
Module 'Wyomind_OrderEraser':
DDL cache cleared successfully

**Comment by adrok** [comment]
setup:upgrade command not completed, data for blog not updated. You need successfully run setup:upgrade before run next commands (Running data migration step not completed..)

**Comment by PaperDS** [comment]
Ok. I'll look into that. thanks

**Comment by PaperDS** [comment]
Ok had a file permissions issue. Fixed now and all working thanks
