### ISSUE TITLE
AddThis iFrame Issue

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [mirasvit/module-blog#5]
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin https://zzz.com from accessing a frame with origin "https://s7.addthis.com". Protocols, domains, and ports must match.

This may help: http://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame

**Comment by adrok** [comment]
I can't reproduce this issue on our demo http://blog.m2.mirasvit.com/blog/

Please try reproduce issue on demo.
