### ISSUE TITLE
Blog menu item

### ISSUE THREAD

**Issue by fwegberts** [mirasvit/module-blog#50]
Hi,

We want to remove the blog item from our main menu. Can you make an option in the module for it? We don't want to edit the module files.

**Comment by andidhouse** [comment]
same here. an option would be great as not everyone need the link in top navigation.

**Comment by RomanZh** [comment]
Done

**Comment by nathanjhastings** [comment]
The option only seems to work if selected at the default store view level. We have a site where we only want the menu link on one site so have switched on the menu visible option for that site store view and off on the other site store view however it only seems to work when selecting the default store view so either shows on both or none at all.
