### ISSUE TITLE
Add products to blog post

### ISSUE THREAD

**Issue by fwegberts** [mirasvit/module-blog#52]
Hi,

I would be nice if there is an option to add some related products to a blog post. 

Can you fix that? :)

**Comment by fwegberts** [comment]
Is possible in the current version, sorry :)

**Comment by RomanZh** [comment]
We already have this feature https://www.screencast.com/t/YXk66FrB . Please check http://blog.m2.mirasvit.com/mageadmin/blog/post/edit/id/36/
