### ISSUE TITLE
DI compile Failing 

### ISSUE THREAD

**Issue by atish2jcommerce** [mirasvit/module-blog#54]
Hello Team,

We have recently download your extension and it working great !!

The problem is we are using Magento Cloud for project hosting, which runs `setup:di:compile` on every deployment.

We are getting as issue from the extension during the compilation process. 

**StackTrace**

`Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 97.0 MiBPHP Fatal error:  Cannot use Magento\Framework\UrlInterface as UrlInterface because the name is already in use in /var/www/html/repos/project-cloud/vendor/mirasvit/module-blog/Model/Config.php on line 8
PHP Stack trace:
PHP   1. {main}() /var/www/html/repos/mick-george-cloud/bin/magento:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/html/repos/mick-george-cloud/bin/magento:23
PHP   3. Magento\Framework\Console\Cli->doRun() /var/www/html/repos/mick-george-cloud/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/html/repos/mick-george-cloud/vendor/magento/framework/Console/Cli.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/html/repos/mick-george-cloud/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/html/repos/mick-george-cloud/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. Magento\Setup\Console\Command\DiCompileCommand->execute() /var/www/html/repos/mick-george-cloud/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   8. Magento\Setup\Module\Di\App\Task\Manager->process() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:188
PHP   9. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
PHP  10. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
PHP  11. class_exists() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:69
PHP  12. spl_autoload_call() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:69
PHP  13. Composer\Autoload\ClassLoader->loadClass() /var/www/html/repos/mick-george-cloud/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:69`

Can please provide any possible solution for this ?

Thanks and Regards

**Comment by RomanZh** [comment]
done. version 1.0.15 released

**Comment by atish2jcommerce** [comment]
@RomanZh  Thanks for quick update, I will update the module version and try it out.

**Comment by atish2jcommerce** [comment]
@RomanZh Its working now thanks for the quick fix.
