### ISSUE TITLE
Usage of OSL license -> Move to MIT

### ISSUE THREAD

**Issue by timneutkens** [mirasvit/module-blog#59]
https://www.gnu.org/licenses/license-list.html#OSL

https://choosealicense.com/licenses/mit/

**Comment by volodymyr-d** [comment]
We use the same licence as magento. We don't plan to change the licence now.
So i'll close this issue.

**Comment by timneutkens** [comment]
> that distributing OSL software on ordinary FTP sites, sending patches to ordinary mailing lists, or storing the software in an ordinary version control system, is arguably a violation of the license and would subject you to possible termination of the license.

would be reason for change when hosting on github, no?

**Comment by samgranger** [comment]
+1
