### ISSUE TITLE
Mobile Navigation not displayed right

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#6]
The navigation (top navigation) on mobile view is not formatted right. 
Two screens attached.

Many thanks!
![2](https://cloud.githubusercontent.com/assets/16196483/13955606/95256a2c-f045-11e5-834a-76da4645a1fd.png)
![1](https://cloud.githubusercontent.com/assets/16196483/13955607/9528be0c-f045-11e5-8b0d-c2bd920545a2.png)

**Comment by adrok** [comment]
Fixed in version 1.0.3 http://blog.m2.mirasvit.com/blog/
