### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by inelukipg** [mirasvit/module-blog#63]
I'm testing different blog extensions for Magento 2 and I have some suggestions for module-blog.

- Function to import Wordpress Blog
- Open Graph Metadata (including image)
- Addthis settings (add your own code)

**Comment by commcad** [comment]
I suggest the less the better ;) As in... so much less to break down eventually. Simplicity Makes Perfect, and that is the reason we like Mirasvit's work so much.

Native and simple stuff, it werks
