### ISSUE TITLE
Add This showing on default landing page

### ISSUE THREAD

**Issue by BeeHealthLimited** [mirasvit/module-blog#68]
```
<?php if ($block->isAddThisEnabled() && !$block->getCategory()): ?>
        <span class="addthis_sharing_toolbox blog__post-meta-sharing"></span>
    <?php endif ?>
```
How do I prevent Addthis showing on "<websiteurl>/blog"?

**Comment by RomanZh** [comment]
You can control displaying of Addthis through blog settings. Please check http://www.screencast.com/t/VwXg6WRNK

**Comment by BeeHealthLimited** [comment]
Yes, however from the above code it does not show when in category view
As you can see here: https://www.fscsupplements.com/blog/Nutrition.html 
However when accessing https://www.fscsupplements.com/blog the Addthis is shown as no category is set.
I would like Addthis enabled, but not shown on the blog landing page.
