### ISSUE TITLE
Wrong formatting on android browser (own and android firefox)

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#7]
The blog list and articles are not formatted right on android browser (own samsung browser and also firefox etc.)

2 Screens attached.
![1](https://cloud.githubusercontent.com/assets/16196483/13992589/f463148a-f11c-11e5-8198-407d32036eaa.png)
![2](https://cloud.githubusercontent.com/assets/16196483/13992590/f4db6872-f11c-11e5-99bc-c7d1b39f2866.png)

**Comment by adrok** [comment]
Fixed.
