### ISSUE TITLE
Root category can be deleted and destroys complete category management

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#72]
It is possible to delete the "root" blog category with the ID1 (we did that).

We created a new root category which has now the ID2 and the complete category structure is not working and showing in the frontend.

I think the extension is programmed that the Root category has the ID1 - once this is deleted it does not work anymore.

How do we fix this again and it would be great if it would be not possible to delete the "root" category any more as you can not recreate this category with the ID1.

**Comment by andidhouse** [comment]
![root](https://user-images.githubusercontent.com/16196483/28265743-94ec76e0-6af1-11e7-8136-ddd54056bae5.png)
![category](https://user-images.githubusercontent.com/16196483/28265744-96e2fad2-6af1-11e7-8fc9-551e61540dba.png)

**Comment by andidhouse** [comment]
The first picture shows the "root" category which has now the ID2 - we deleted the original root category with the ID1.

Now no category can be assigned to a parent category (screen2). 

How can we fix this in the database?

Thanks!

**Comment by RomanZh** [comment]
Hi,

You can create root category in any time you want. But after that you should create new root category. To create root category just create category without parent. As root category was changed you should reassign all subcategories to new root category.

Regards

**Comment by andidhouse** [comment]
Hi Roman,

you are right. If we recreate the root category it is possible to resign the other categories.
BUT:

- Now in the breadcrumbs the "new" root category is also shown 
- And the categories overview on each page are not visible (also the categories are of course active they are not visible at the blog

I think there is still a problem when deleting the default root category.

**Comment by andidhouse** [comment]
![base](https://user-images.githubusercontent.com/16196483/28268990-a8ebc6b4-6b00-11e7-9e05-2b1e0808b348.png)
I think this is a problem of the new root category created as this root (in our example called "base" now has a url field (which makes no sense) and also has a parent category select which is normally a required field but also now works without choosing this.

I think the root should not have a:

1. url
2. a parent category field

And this is i think where the problems come from if you recreate a new root after deleting the original.

Is there any simple way to reinstall the extension so it is working?

**Comment by andidhouse** [comment]
![base-1](https://user-images.githubusercontent.com/16196483/28269106-1c70f92e-6b01-11e7-8676-2f0997c48cf3.png)

**Comment by andidhouse** [comment]
IN comparison to our "new root" category your demo root category shown no "parent category option":

![bildschirmfoto 2017-07-17 um 15 07 25](https://user-images.githubusercontent.com/16196483/28269291-d45fb21e-6b01-11e7-938c-6442717a1335.png)

**Comment by andidhouse** [comment]
We tested this now on three different shops - all get the same problem when deleting the default root category.

@RomanZh could you pls check this - we really need it to go live. Many thanks!

**Comment by RomanZh** [comment]
@andidhouse we will check it and notify about results on this week

**Comment by andidhouse** [comment]
Thanks great!

**Comment by RomanZh** [comment]
We have fixed the issue and released module 'blog' version 1.0.19-beta. Please, update the module.

**Comment by andidhouse** [comment]
Hi Roman,

the "beta" can not be updated by the normal "composer update" string right?

What is here to set to just update the blog in beta mode and not load other composer packages in "beta" mode as well?

Thanks!

**Comment by RomanZh** [comment]
You can use this command 

composer require mirasvit/module-blog:1.0.19-beta
