### ISSUE TITLE
There is no option to sort the categories

### ISSUE THREAD

**Issue by andidhouse** [mirasvit/module-blog#73]
For example create 5 categories.
In the frontend this is showed in the order you created the categories:

1. Cat1
2. Cat2
3. Cat4
4. Cat4
5. Cat5

Lets say you want to create a new category which should be placed between category 1 and 2.
This is not possible as there i no order function in the categories.

**Comment by RomanZh** [comment]
We have added this feature and released module 'blog' version 1.0.19-beta. Please, update the module.
