### ISSUE TITLE
Issue with Post creation form at Admin Panel

### ISSUE THREAD

**Issue by gorillagroup** [mirasvit/module-blog#75]
Hello,

We have Blog extension (1.0.19) installed on Magento 2.1.7

We see there an issue with New Post form:
![screen shot 2017-08-15 at 16 54 19](https://user-images.githubusercontent.com/14338522/29318850-6dc5c8f0-81da-11e7-93eb-a7755cbdaf04.png)

Can you please help with this?

**Comment by RomanZh** [comment]
Hello,

Sorry but we can not reproduce this issue. Did you follow all steps from installation instruction? Also try to clean your cache

Regards

**Comment by gorillagroup** [comment]
Hi, we updated Magento to 2.1.8 and issue disappeared. I'm going to close this ticket.
