### ISSUE TITLE
Category names not translatable / store view specific.

### ISSUE THREAD

**Issue by reviskar** [mirasvit/module-blog#86]
It seems that there is no way to show category names differently for different store views. This would be a must-have for multilingual sites. 

Also this brings us to a related (bigger) issue. We have multisites set-up and for each site we need a totally different blog category system. As I understand, this is not supported?

**Comment by dazz397** [comment]
I had this same issue. I have 2 websites and I ended up with 3 different categories named blog. I am assuming one for each website(default config, website1, website2). I just made one child under each "blog" category and restricted each blog post to a specific view and it works but the categorization definitely has an issue and is not multisite compatible.

**Comment by reviskar** [comment]
Yeah, by now I've created my own plugin-module, that enables store-view specific categories. Created it pretty much exactly as the post object, except used a different adminhtml form for store-ids. (I used the store_id multiselect, because we may need some same categories in different stores)

**Comment by istoutjesdijk** [comment]
Wil this be implemented in a future version of Blox MX?
