### ISSUE TITLE
Show xx per page shows twice

### ISSUE THREAD

**Issue by dazz397** [mirasvit/module-blog#87]
At the bottom of the blog list "Show xx per page" shows twice.  If you view source you see the code is listed twice but the second time it shows <=$_key ?> instead of the value. 

```html
<div class="limiter">
<strong class="limiter-label">Show</strong>
<select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
<option value="http://demo.com/blog/?limit=10" selected="selected">10</option>
<option value="http://demo.com/blog/?limit=20">20</option>
<option value="http://demo.com/blog/?limit=50">50</option>
</select>
<span class="limiter-text">per page</span>
</div>

<div class="field limiter">
<label class="label" for="limiter">
<span>Show</span>
</label>
<div class="control">
<select id="limiter" data-role="limiter" class="limiter-options">
<option value="<=$_key ?>" selected="selected">10</option>
<option value="<=$_key ?>">20</option>
<option value="<=$_key ?>">50</option>
</select>
</div>
```

**Comment by wjpbill** [comment]
Same issue here on a site I've just put together using the Ultimo theme, any update on this?

![capture](https://user-images.githubusercontent.com/39123930/39813339-eeabd3ae-5387-11e8-9712-f7f5df353d8f.PNG)

**Comment by wjpbill** [comment]
I've found where it's coming from.

It's being caused by line 8 in 

module-blog\view\frontend\templates\post\list\toolbar.phtml

It's not even written the same code standard as the rest of the module and looks like someone added it 

I've removed it from mine and all ok now
