### ISSUE TITLE
bluefoot not working

### ISSUE THREAD

**Issue by raybogman** [mirasvit/module-blog#88]
Dear Support,

Just read your post on bluefoothttps://mirasvit.com/blog/blogging-doesnt-get-better-than-this-use-blog-mx-with-the-bluefoot-pagebuilder.html 

I am using a vanilla M2.2.1 incl bluefoot and I don't see a bluefoot button. the blog doesnot explain how to activate it. 

Thanx allready 4 the help

**Comment by juho-jaakkola** [comment]
What is the status of this issue?

**Comment by juho-jaakkola** [comment]
The fix was to add this patch to the `Gene_BlueFoot` module:

```diff
diff --git a/etc/di.xml b/etc/di.xml
index 6f3016c..053e2f6 100644
--- a/etc/di.xml
+++ b/etc/di.xml
@@ -38,6 +38,7 @@
             <argument name="supportedModules" xsi:type="array">
                 <item name="Magento_Cms" xsi:type="string">Magento_Cms</item>
                 <item name="Magento_VersionsCms" xsi:type="string">Magento_VersionsCms</item>
+                <item name="Mirasvit_Blog" xsi:type="string">Mirasvit_Blog</item>
             </argument>
         </arguments>
     </type>
```
