### ISSUE TITLE
Associate a Post with a Product

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#9]
Nice features to look at are here and here...:
https://github.com/IhorVansach/Blog-Extension-for-Magento-2
https://www.magearray.com/blog-magento-2-extension.html
https://www.solwininfotech.com/product/magento-2-extensions/advanced-blog-magento-2/

One of these would be very nice - Associate a Post with a Product.
Bidirectional Linking for Blog Posts <> Products, New Tab on a Product page, if it has associated Blog Post, showing Post excerpt with image thumbnail and a link to view full Blog post

**Comment by adrok** [comment]
Implemented in version 1.0.4-alpha2

**Product page**
![image](https://cloud.githubusercontent.com/assets/1307119/14045338/09087e80-f2a2-11e5-8eb9-24cbe4e04d04.png)

**Post edit page**
![image](https://cloud.githubusercontent.com/assets/1307119/14045362/3c8f675a-f2a2-11e5-8ccd-87f55e7202e3.png)

**Comment by devdesco-ceo** [comment]
You are a genius!
