### ISSUE TITLE
getFeaturedShowOnHome missing in Model

### ISSUE THREAD

**Issue by Kroellie** [mirasvit/module-blog#91]

**Comment by Kroellie** [comment]
at least, that's my guess... there are more methods missing apparently...

**Comment by RomanZh** [comment]
HI,

featured_show_on_home - is eav attribute of post object.

**Comment by Kroellie** [comment]
Whatever it is, it's not working :) at first post, the setting = 0. Post is not showing on Home. Re-editing sets the value to 1. Upon saving it is showing on Home. Then re-editing again, setting it to 0, doesn't do anything.
