### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_at' cannot be null

### ISSUE THREAD

**Issue by bartekszymanski** [mirasvit/module-blog#92]
During create new post on fresh install. 
Magento ver. 2.2.2

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_at' cannot be null, query was: INSERT INTO `mst_blog_post_entity` (`author_id`, `type`, `parent_id`, `created_at`, `updated_at`) VALUES (?, ?, ?, NULL, '2018-01-21 09:37:18')`

**Comment by Tjitse-E** [comment]
@bartekszymanski i've got the same issue here. Did you find out the cause of the error?

**Comment by bartekszymanski** [comment]
Take a look:
https://github.com/mirasvit/module-blog/blob/92c85f8eac42e5c00176c2656942f1a659dd6f9c/Controller/Adminhtml/Post/Save.php#L82

Condition doesn't check data in `$result['created_at']` so it may return wrong data in `$formatter->parse($result['created_at'])`

**Comment by Tjitse-E** [comment]
Thanks for your reply!

I've added a check in the `_beforeSave` method and that seems to work.
