### ISSUE TITLE
#IBX-508-69469- ссылка на блог не появилась в меню

### ISSUE THREAD

**Issue by VikMirasvit** [mirasvit/module-blog#99]
### Проблема

- [ ] Ссылка на блог не появилась. Клиент просит добавить. 

### Доступы
#IBX-508-69469

### Дополнительно

**Comment by adrok** [comment]
@VikMirasvit http://prntscr.com/ikujxa - локально ссылка есть, может у него не дефолтное меню - но это уже не к нам .
